<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import { postToHost, subscribeToHost, type WebViewMessage } from './bridge';
import HomePage from './pages/HomePage.vue';
import ActivitiesPage from './pages/ActivitiesPage.vue';
import ScoresPage from './pages/ScoresPage.vue';
import ShopPage from './pages/ShopPage.vue';
import CheckinPage from './pages/CheckinPage.vue';
import SocialPage from './pages/SocialPage.vue';
import AimePage from './pages/AimePage.vue';
import SettingsDialogs, { type DisplayOption, type LauncherSettings, type SaveSettingsPayload } from './components/SettingsDialogs.vue';
import type { EventSlide, NewsTab, ViewAction } from './components/types';

const eventSlides: EventSlide[] = [
  { image: './assets/events/event-doki.png', date: '09.25 — 10.06', title: '9/25(周五)《心跳文学部！》联动活动开始！', body: '今天9/22(周二)是莫妮卡的生日！\n为了纪念生日，将举办《心跳文学部！》联动活动！\n9/25(周五)起，「Your Reality (Kenji Mizuno Remix)」将登场！\n活动期间可获得《心跳文学部！》的角色、名牌以及舞台背景！' },
  { image: './assets/events/event-songs.png', date: '09.25', title: '9/25(周五) 曲目新增！', body: '从9/25(周五)起，POPS＆ANIME中「LaVI-Bavellabion」，VARIETY中「奇々解体」将在CHUNITHM登场！\n此外，大受欢迎的曲目「きゅうくらりん」将以「ULTIMA」强化版登场哦！\n一定要来玩玩看呢！' },
  { image: './assets/events/event-iyowa.png', date: '09.25 — 11.11', title: '9/25(周五)『いよわ』联名活动重启！', body: '9/25(周五)起，『いよわ』的活动地图重启！\n在地图中，过去活动中获得的角色将再次可获得，而且还能获得舞台背景哦！\n抓住这个机会一起玩吧！' },
  { image: './assets/events/event-emperor.png', date: '09.10 — 09.13', title: '全国对战活动 ～ 盟帝「第9回 皇帝活动」结果公布！', body: '9/10(周四)～9/13(周日)举办的「第9回 皇帝活动」中排名靠前的用户大公布！\n※称号已发放完毕。\n官方站点的排行榜页面已更新！' },
  { image: './assets/events/event-maimai.png', date: '09.17 — 09.30', title: '9月17日(周四)「maimai でらっくす」联动活动举办！', body: '为了纪念《maimai でらっくす MAGiCAL》的启动，我们将开始maimai でらっくす的联动活动！\n活动期间，每天玩maimai でらっくす的日子，在CHUNITHM中可以获得1张【当日限定】SPECIALチケット，每天1张哦！请一定要来玩玩看吧！' },
];
const newsTabs: Record<NewsTab, { title: string; date: string }[]> = { activities: [{ title: '「心跳文学部！」联动活动开始', date: '09/25' }, { title: '活动限定角色与名牌开放获取', date: '09/25' }], announcements: [{ title: 'CHUNITHM Launcher 前端工作台更新', date: '09/22' }, { title: '社区活动公告已更新', date: '09/21' }], updates: [{ title: '社区内容展示页开放投稿', date: '09/14' }, { title: '版本 2.5.0 更新说明', date: '09/08' }] };
const navItems = [['home', '⌂', '首页'], ['activities', '✦', '活动'], ['scores', '◈', '查分'], ['shop', '▣', '商城'], ['social', '♧', '好友'], ['aime', '◎', 'Aime'], ['checkin', '☼', '签到']] as const;
const activeView = ref('home'); const eventIndex = ref(0); const newsTab = ref<NewsTab>('activities');
const theme = ref<'light' | 'dark'>((localStorage.getItem('chunithm-theme') as 'light' | 'dark') || 'light');
const version = ref('preview'); const statusText = ref('待机'); const statusColor = ref('#5caa74'); const showSettings = ref(false); const showFirstRun = ref(false);
const settings = ref<LauncherSettings>({ startBatPath: '', primaryDisplay: '', primaryDisplayName: '未选择', originalMode: '', targetMode: '1920×1080 @ 120Hz', launchMode: 'smart', smartDisplayEnabled: false, runBatAsAdministrator: true, terminateCmdBeforeLaunch: true, themeColor: '#fdd500', backgroundImagePath: '' });
const displays = ref<DisplayOption[]>([]); const portalButtonText = ref(localStorage.getItem('chunithm-portal-text') || '打开MuNET'); const portalUrl = ref(localStorage.getItem('chunithm-portal-url') || 'https://portal.mumur.net/');
const announcement = ref<{ title: string; body: string; url?: string; label?: string } | null>(null);
function applyTheme(next: 'light' | 'dark'): void { theme.value = next; localStorage.setItem('chunithm-theme', next); document.body.classList.toggle('dark-mode', next === 'dark'); }
function selectView(view: string): void { activeView.value = view; document.querySelector('.view-stack')?.scrollTo({ top: 0, behavior: 'smooth' }); }
function handleInit(payload: Record<string, unknown>): void { version.value = String(payload.version || 'preview'); displays.value = (payload.displays as DisplayOption[]) || []; const selectedDisplay = displays.value.find((display) => display.selected); settings.value = { ...settings.value, ...payload, primaryDisplay: selectedDisplay?.id || settings.value.primaryDisplay, primaryDisplayName: String(payload.primaryDisplayName || selectedDisplay?.name || settings.value.primaryDisplayName || '未选择') } as LauncherSettings; showFirstRun.value = !settings.value.startBatPath || !settings.value.primaryDisplay; if (settings.value.themeColor) document.documentElement.style.setProperty('--accent', settings.value.themeColor); }
function handleHostMessage(message: WebViewMessage): void { const payload = (message.payload || {}) as Record<string, unknown>; if (message.type === 'init') handleInit(payload); if (message.type === 'status') { statusText.value = String(payload.text || '待机'); statusColor.value = String(payload.color || '#5caa74'); } if (message.type === 'announcement') { const action = payload.action as { url?: string; label?: string } | undefined; const title = String(payload.title || '').trim(); const body = String(payload.body || '').trim(); if (title && body) announcement.value = { title, body, url: action?.url, label: action?.label }; } if (message.type === 'update-target') settings.value.targetMode = String(payload.value || ''); if (message.type === 'update-original') settings.value.originalMode = String(payload.value || ''); if (message.type === 'update-start-bat') settings.value.startBatPath = String(payload.path || ''); if (message.type === 'update-background-image') settings.value.backgroundImagePath = String(payload.path || ''); if (message.type === 'update-displays') { displays.value = (payload.displays as DisplayOption[]) || []; settings.value.primaryDisplayName = String(payload.primaryDisplayName || '未选择'); } }
function action(name: ViewAction): void { if (name === 'launch-game') postToHost('launch-game'); else if (name === 'view-activity') selectView('activities'); else if (name === 'open-checkin') selectView('checkin'); else if (name === 'open-scores' || name === 'view-recommendation') selectView('scores'); else if (name === 'view-profile') selectView('social'); else if (name === 'open-aime-project') window.open('https://github.com/Luckyumimi/NfcAimeReader', '_blank', 'noopener,noreferrer'); }
function saveSettings(payload: SaveSettingsPayload): void { settings.value = { ...settings.value, ...payload }; }
function onMuNetChange(payload: { text: string; url: string }): void { portalButtonText.value = payload.text; portalUrl.value = payload.url; localStorage.setItem('chunithm-portal-text', payload.text); localStorage.setItem('chunithm-portal-url', payload.url); }
function openPortal(): void { try { const url = new URL(portalUrl.value); if (!/^https?:$/.test(url.protocol)) throw new Error(); postToHost('open-munet', { url: url.href }); } catch { statusText.value = '网页链接格式不正确'; statusColor.value = '#bd5f68'; } }
function hasAnnouncementAction(url?: string): boolean { return !!url && /^https:\/\//i.test(url); }
watch(() => settings.value.backgroundImagePath, (path) => { document.documentElement.style.setProperty('--user-bg', path ? `url("${path.replaceAll('\\', '/')}")` : 'none'); }, { immediate: true });
watch(() => settings.value.themeColor, (color) => { if (color) document.documentElement.style.setProperty('--accent', color); }, { immediate: true });
let unsubscribe = (): void => undefined; onMounted(() => { applyTheme(theme.value); unsubscribe = subscribeToHost(handleHostMessage); }); onUnmounted(() => unsubscribe());
const currentPage = computed(() => ({ home: HomePage, activities: ActivitiesPage, scores: ScoresPage, shop: ShopPage, social: SocialPage, aime: AimePage, checkin: CheckinPage }[activeView.value] || HomePage));
</script>
<template>
  <div class="page" :class="{ dark: theme === 'dark', 'has-user-background': !!settings.backgroundImagePath }" :style="{ '--accent': settings.themeColor || '#fdd500' }">
    <div class="texture" /><main class="launcher-shell"><aside class="launcher-rail" aria-label="主导航"><button class="rail-brand" type="button" @click="selectView('home')"><span>CHU</span><b>0</b></button><nav class="rail-nav"><button v-for="[view, icon, label] in navItems.slice(0, 6)" :key="view" class="rail-link" :class="{ active: activeView === view }" type="button" @click="selectView(view)"><span class="rail-icon">{{ icon }}</span><span>{{ label }}</span></button></nav><div class="rail-bottom"><button class="rail-link" :class="{ active: activeView === 'checkin' }" type="button" @click="selectView('checkin')"><span class="rail-icon">☼</span><span>签到</span></button><button class="rail-link" type="button" @click="showSettings = true"><span class="rail-icon">⚙</span><span>设置</span></button></div></aside>
      <section class="launcher-stage"><header class="topbar"><div class="stage-kicker"><span class="live-dot" /><span>CHUNITHM COMMUNITY HUB</span></div><div class="top-actions"><span class="status-pill"><i :style="{ background: statusColor }" /><span>{{ statusText }}</span></span><button class="app-button theme-button" type="button" @click="applyTheme(theme === 'dark' ? 'light' : 'dark')">{{ theme === 'dark' ? '浅色' : '深色' }}</button><button class="app-button account-button" type="button"><span class="account-avatar">C</span><span>演示账户　Lv.12</span></button><button class="app-button" type="button" @click="openPortal">{{ portalButtonText }}</button></div></header>
        <div class="view-stack"><component :is="currentPage" :event-slides="eventSlides" :event-index="eventIndex" :news-tab="newsTab" :news-tabs="newsTabs" @event-change="eventIndex = $event" @news-tab-change="newsTab = $event" @action="action"><template #launch-status><article class="status-panel app-panel"><div class="target-label">目标模式</div><div class="target-value">{{ settings.targetMode }}</div><div class="stats"><div><span>原始分辨率</span><b>{{ settings.originalMode || '未读取' }}</b></div><div><span>主显示器</span><b>{{ settings.primaryDisplayName || '未选择' }}</b></div></div><label class="target-label launch-mode-label">启动模式</label><div class="segmented" :data-mode="settings.launchMode"><button type="button" :class="{ active: settings.launchMode === 'smart' }" @click="settings.launchMode = 'smart'; postToHost('set-launch-mode', { mode: 'smart' })">智能切换</button><button type="button" :class="{ active: settings.launchMode !== 'smart' }" @click="settings.launchMode = 'manual'; postToHost('set-launch-mode', { mode: 'manual' })">仅启动</button></div><div class="bottom-controls"><label class="checkbox"><input v-model="settings.smartDisplayEnabled" type="checkbox" @change="postToHost('set-smart-display', { enabled: settings.smartDisplayEnabled })" /><span />独占显示器</label><button class="app-button compact" type="button" @click="postToHost('test-switch')">测试切换</button></div></article></template></component></div><footer><span>v{{ version }}</span><span>CHUNITHM Launcher / Thesis Edition</span></footer></section></main>
    <SettingsDialogs :settings="settings" :displays="displays" :theme="theme" :show-settings="showSettings" :show-first-run="showFirstRun" @save-settings="saveSettings" @complete-first-run="saveSettings" @close-settings="showSettings = false" @update:show-settings="showSettings = $event" @update:show-first-run="showFirstRun = $event" @theme-change="applyTheme" @mu-net-change="onMuNetChange" @open-donation="postToHost('open-github-home')" />
    <div v-if="announcement" class="modal-backdrop show" role="presentation" @click.self="announcement = null"><section class="modal-card announcement-card" role="dialog" aria-modal="true"><div class="modal-heading"><div><h2>{{ announcement.title }}</h2><small>项目公告</small></div><button class="app-button" type="button" @click="announcement = null">关闭</button></div><p class="announcement-body">{{ announcement.body }}</p><div v-if="hasAnnouncementAction(announcement.url)" class="announcement-actions"><button class="app-button primary" type="button" @click="postToHost('open-announcement-link', { url: announcement?.url }); announcement = null">{{ announcement.label || '查看详情' }}</button></div></section></div>
  </div>
</template>
